modLoader = "javafml"
loaderVersion = "[46.0.0,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "playeranimator"
version = "${version}"
displayName = "Player Animator"
authors = "KosmX"
description = '''
Look for FabricMC (or QuiltMC) builds...
'''
#logoFile = ""

[[dependencies.playeranimator]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"
