modLoader = "javafml"
loaderVersion = "*"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "playeranimator"
version = "${version}"
displayName = "Player Animator"
authors = "KosmX"
description = "A lightweight library to easily animate the player"
#logoFile = ""

[[dependencies.playeranimator]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"
